export enum BreadCrumbsTypes {
  SET_BREAD_CRUMBS = "BREAD_CRUMBS:SET",
  DROP_BREAD_CRUMBS = "BREAD_CRUMBS:DROP"
}

export enum TokenTypes {
  GET_JWTTOKEN = "TOKEN:GET",
  CHECK_TOKEN = "TOKEN:CHECK"
}